name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        # Sesuaikan 'nama_folder_proyek' dengan nama folder tempat pubspec.yaml berada
        working-directory: ./nama_folder_proyek  
        run: flutter pub get

      - name: Build APK
        working-directory: ./nama_folder_proyek
        run: flutter build apk --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aplikasi-speedometer-apk
          path: nama_folder_proyek/build/app/outputs/flutter-apk/app-release.apk
